//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Adress
{
	public virtual City City
	{
		get;
		set;
	}

	public virtual Street Street
	{
		get;
		set;
	}

	public virtual int Flat
	{
		get;
		set;
	}

	/// <summary>
	/// Подъезд дома
	/// </summary>
	public virtual int FrontDoor
	{
		get;
		set;
	}

}

