//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public City City
	{
		get;
		set;
	}

	public Street Street
	{
		get;
		set;
	}

	public int Flat
	{
		get;
		set;
	}

	/// <summary>
	/// Подъезд дома
	/// </summary>
	public int FrontDoor
	{
		get;
		set;
	}

}

