//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using References;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public sealed class Client
{
	/// <summary>
	/// Доступ
	/// </summary>
	public string Access
	{
		get;
		set;
	}

	/// <summary>
	/// Фамилия
	/// </summary>
	public string Surname
	{
		get;
		set;
	}

	/// <summary>
	/// Адреса
	/// </summary>
	public IEnumerable<Address> Addresses
	{
		get;
		set;
	}

	/// <summary>
	/// Номер счета
	/// </summary>
	public string ScoreName
	{
		get;
		set;
	}

	/// <summary>
	/// Абонентский номер
	/// </summary>
	public string SubscriberNumber
	{
		get;
		set;
	}

	/// <summary>
	/// Дата рождения
	/// </summary>
	public DateTime DateOfBirth
	{
		get;
		set;
	}

	/// <summary>
	/// Отчество
	/// </summary>
	public string Patronymic
	{
		get;
		set;
	}

	/// <summary>
	/// Имя
	/// </summary>
	public string Name
	{
		get;
		set;
	}

	/// <summary>
	/// Номер телефона
	/// </summary>
	public IEnumerable<String> Phones
	{
		get;
		set;
	}

	/// <summary>
	/// Подсчет заказов
	/// </summary>
	public IEnumerable<Order> Orders
	{
		get;
		set;
	}

	/// <summary>
	/// Подсчет заказов
	/// </summary>
	public Bool CountingOrders
	{
		get;
		set;
	}

	/// <summary>
	/// Последнее время пользования
	/// </summary>
	public DateTime LastUseDateTime
	{
		get;
		set;
	}

	/// <summary>
	/// Баланс
	/// </summary>
	public decimal Balance
	{
		get;
		set;
	}

	/// <summary>
	/// Форма оплаты
	/// </summary>
	public string MethodOfPayment
	{
		get;
		set;
	}

	/// <summary>
	/// Тип скидки
	/// </summary>
	public DiscountType DiscountType
	{
		get;
		set;
	}

	/// <summary>
	/// Размер скидки
	/// </summary>
	public decimal DiscountValue
	{
		get;
		set;
	}

	/// <summary>
	/// Дата создатия
	/// </summary>
	public DateTime CreatingDateTime
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки водителя
	/// </summary>
	public string NotesDriver
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки
	/// </summary>
	public string Notes
	{
		get;
		set;
	}

	/// <summary>
	/// Номер
	/// </summary>
	public int Number
	{
		get;
		set;
	}

	/// <summary>
	/// Род занятий
	/// </summary>
	public string Occupation
	{
		get;
		set;
	}

	/// <summary>
	/// Электронная почта
	/// </summary>
	public string Email
	{
		get;
		set;
	}

	/// <summary>
	/// Заблокирован
	/// </summary>
	public bool Blocked
	{
		get;
		set;
	}

	/// <summary>
	/// Ваучер
	/// </summary>
	public bool Voucher
	{
		get;
		set;
	}

	/// <summary>
	/// Индекс
	/// </summary>
	public decimal Index
	{
		get;
		set;
	}

	/// <summary>
	/// Возврат
	/// </summary>
	public decimal Return
	{
		get;
		set;
	}

	/// <summary>
	/// Наценка НДС
	/// </summary>
	public decimal VARMarkup
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки GPRS
	/// </summary>
	public string NotesGPRS
	{
		get;
		set;
	}

	/// <summary>
	/// Запрет на изменение поля WebOrdes
	/// </summary>
	public bool BanOnTheChangeWebOrders
	{
		get;
		set;
	}

	public decimal BonusForOrder
	{
		get;
		set;
	}

	/// <summary>
	/// Тип бонуса за заказ
	/// </summary>
	public BonusForOrderType BonusForOrderType
	{
		get;
		set;
	}

	/// <summary>
	/// Статус клиента
	/// </summary>
	public Status Status
	{
		get;
		set;
	}

}

