//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using References;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Client
{
	/// <summary>
	/// Доступ
	/// </summary>
	public virtual string Access
	{
		get;
		set;
	}

	/// <summary>
	/// Фамилия
	/// </summary>
	public virtual string Surname
	{
		get;
		set;
	}

	/// <summary>
	/// Адреса
	/// </summary>
	public virtual IEnumerable<Address> Addresses
	{
		get;
		set;
	}

	/// <summary>
	/// Номер счета
	/// </summary>
	public virtual string ScoreName
	{
		get;
		set;
	}

	/// <summary>
	/// Абонентский номер
	/// </summary>
	public virtual string SubscriberNumber
	{
		get;
		set;
	}

	/// <summary>
	/// Дата рождения
	/// </summary>
	public virtual DateTime DateOfBirth
	{
		get;
		set;
	}

	/// <summary>
	/// Отчество
	/// </summary>
	public virtual string Patronymic
	{
		get;
		set;
	}

	/// <summary>
	/// Имя
	/// </summary>
	public virtual string Name
	{
		get;
		set;
	}

	/// <summary>
	/// Номер телефона
	/// </summary>
	public virtual IEnumerable<String> Phones
	{
		get;
		set;
	}

	/// <summary>
	/// Подсчет заказов
	/// </summary>
	public virtual IEnumerable<Order> Orders
	{
		get;
		set;
	}

	/// <summary>
	/// Подсчет заказов
	/// </summary>
	public virtual Bool CountingOrders
	{
		get;
		set;
	}

	/// <summary>
	/// Последнее время пользования
	/// </summary>
	public virtual DateTime LastUseDateTime
	{
		get;
		set;
	}

	/// <summary>
	/// Баланс
	/// </summary>
	public virtual decimal Balance
	{
		get;
		set;
	}

	/// <summary>
	/// Форма оплаты
	/// </summary>
	public virtual string MethodOfPayment
	{
		get;
		set;
	}

	/// <summary>
	/// Тип скидки
	/// </summary>
	public virtual DiscountType DiscountType
	{
		get;
		set;
	}

	/// <summary>
	/// Размер скидки
	/// </summary>
	public virtual decimal DiscountValue
	{
		get;
		set;
	}

	/// <summary>
	/// Дата создатия
	/// </summary>
	public virtual DateTime CreatingDateTime
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки водителя
	/// </summary>
	public virtual string NotesDriver
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки
	/// </summary>
	public virtual string Notes
	{
		get;
		set;
	}

	/// <summary>
	/// Номер
	/// </summary>
	public virtual int Number
	{
		get;
		set;
	}

	/// <summary>
	/// Род занятий
	/// </summary>
	public virtual string Occupation
	{
		get;
		set;
	}

	/// <summary>
	/// Электронная почта
	/// </summary>
	public virtual string Email
	{
		get;
		set;
	}

	/// <summary>
	/// Заблокирован
	/// </summary>
	public virtual bool Blocked
	{
		get;
		set;
	}

	/// <summary>
	/// Ваучер
	/// </summary>
	public virtual bool Voucher
	{
		get;
		set;
	}

	/// <summary>
	/// Индекс
	/// </summary>
	public virtual decimal Index
	{
		get;
		set;
	}

	/// <summary>
	/// Возврат
	/// </summary>
	public virtual decimal Return
	{
		get;
		set;
	}

	/// <summary>
	/// Наценка НДС
	/// </summary>
	public virtual decimal VARMarkup
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки GPRS
	/// </summary>
	public virtual string NotesGPRS
	{
		get;
		set;
	}

	/// <summary>
	/// Запрет на изменение поля WebOrdes
	/// </summary>
	public virtual bool BanOnTheChangeWebOrders
	{
		get;
		set;
	}

	public virtual decimal BonusForOrder
	{
		get;
		set;
	}

	/// <summary>
	/// Тип бонуса за заказ
	/// </summary>
	public virtual BonusForOrderType BonusForOrderType
	{
		get;
		set;
	}

	/// <summary>
	/// Статус клиента
	/// </summary>
	public virtual Status Status
	{
		get;
		set;
	}

}

