//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Начисл. При отсутсвии выпол. Заказов
/// </summary>
public class DriverFeeMissingOrder
{
	/// <summary>
	/// Абоплата
	/// </summary>
	public virtual string SubscriberFee
	{
		get;
		set;
	}

	/// <summary>
	/// Рация
	/// </summary>
	public virtual string Radio
	{
		get;
		set;
	}

	/// <summary>
	/// Аренда
	/// </summary>
	public virtual string Rent
	{
		get;
		set;
	}

}

