//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Разрешения
/// </summary>
public class DriverAccessSetting
{
	/// <summary>
	/// Постановка в секторе
	/// </summary>
	public virtual bool SetInSector
	{
		get;
		set;
	}

	/// <summary>
	/// Автопостановка на заказ посектору (заказы СОЗ)
	/// </summary>
	public virtual bool AutoOrderSectorPOPOrders
	{
		get;
		set;
	}

	/// <summary>
	/// Автопостановка на заказ по GPS (заказы СОЗ)
	/// </summary>
	public virtual bool AutoOrderByGPSPOPsOrders
	{
		get;
		set;
	}

	/// <summary>
	/// Постановка/Автопостановка на заказ по GPS (Свои заказы)
	/// </summary>
	public virtual bool AutoProductionToOrderOnGPSHisOrders
	{
		get;
		set;
	}

	/// <summary>
	/// Автовзятие с телефона
	/// </summary>
	public virtual bool AutoAnswerPhone
	{
		get;
		set;
	}

	/// <summary>
	/// Оплата комиссионных через терминал
	/// </summary>
	public virtual bool PaymentOfFeesThroughTerminal
	{
		get;
		set;
	}

	/// <summary>
	/// Конференц связь с клиентом
	/// </summary>
	public virtual bool ConferenceConnectionWithClient
	{
		get;
		set;
	}

}

