//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// По совместительству
/// </summary>
public class DriverConcurrently
{
	/// <summary>
	/// Мин. Сдача комисс.
	/// </summary>
	public virtual decimal MinimumDepositCommission
	{
		get;
		set;
	}

	/// <summary>
	/// если вып. Зак. Менее
	/// </summary>
	public virtual int MinimumCompleteOrders
	{
		get;
		set;
	}

	/// <summary>
	/// По совместительству
	/// </summary>
	public virtual bool On
	{
		get;
		set;
	}

}

