//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using References;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Driver
{
	/// <summary>
	/// Паспорт
	/// </summary>
	public virtual string Pasport
	{
		get;
		set;
	}

	/// <summary>
	/// Фамилия
	/// </summary>
	public virtual string Surname
	{
		get;
		set;
	}

	/// <summary>
	/// Имя
	/// </summary>
	public virtual string Name
	{
		get;
		set;
	}

	/// <summary>
	/// Отчество
	/// </summary>
	public virtual string Patronymic
	{
		get;
		set;
	}

	/// <summary>
	/// Псевдоним
	/// </summary>
	public virtual string Nickname
	{
		get;
		set;
	}

	/// <summary>
	/// Позывной
	/// </summary>
	public virtual string Callsign
	{
		get;
		set;
	}

	/// <summary>
	/// Адреса
	/// </summary>
	public virtual IEnumerable<Address> Addresses
	{
		get;
		set;
	}

	/// <summary>
	/// Заметки
	/// </summary>
	public virtual string Notes
	{
		get;
		set;
	}

	/// <summary>
	/// Диспетчер
	/// </summary>
	public virtual DispatcherType DispatcherType
	{
		get;
		set;
	}

	/// <summary>
	/// GPRS
	/// </summary>
	public virtual bool GPRS
	{
		get;
		set;
	}

	/// <summary>
	/// Рация
	/// </summary>
	public virtual bool RadioSet
	{
		get;
		set;
	}

	/// <summary>
	/// День рожденья
	/// </summary>
	public virtual DateTime DateOfBirthday
	{
		get;
		set;
	}

	/// <summary>
	/// Принят наработу
	/// </summary>
	public virtual DateTime Adopted
	{
		get;
		set;
	}

	/// <summary>
	/// Уволен
	/// </summary>
	public virtual DateTime Fired
	{
		get;
		set;
	}

	/// <summary>
	/// Пароль
	/// </summary>
	public virtual string Password
	{
		get;
		set;
	}

	/// <summary>
	/// Разрешения
	/// </summary>
	public virtual DriverAccessSetting DriverAccessSetting
	{
		get;
		set;
	}

	/// <summary>
	/// Дополнительно
	/// </summary>
	public virtual DriverAdditionalSetting DriverAdditionalSetting
	{
		get;
		set;
	}

	/// <summary>
	/// Сдал залог
	/// </summary>
	public virtual decimal PassedPledge
	{
		get;
		set;
	}

	/// <summary>
	/// Долг залог
	/// </summary>
	public virtual decimal DebtPledge
	{
		get;
		set;
	}

	public virtual DriverPersonalCommission DriverPersonalCommission
	{
		get;
		set;
	}

	/// <summary>
	/// Абонплата с заказа, гр
	/// </summary>
	public virtual DriverFeeToOrder DriverFeeToOrder
	{
		get;
		set;
	}

	/// <summary>
	/// Номер телефона
	/// </summary>
	public virtual IEnumerable<String> Phones
	{
		get;
		set;
	}

	/// <summary>
	/// По совместительству
	/// </summary>
	public virtual DriverConcurrently DriverConcurrently
	{
		get;
		set;
	}

}

