//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Абонплата с заказа, гр
/// </summary>
public class DriverFeeToOrder
{
	/// <summary>
	/// Со своего
	/// </summary>
	public virtual decimal Your
	{
		get;
		set;
	}

	/// <summary>
	/// С прекидочного
	/// </summary>
	public virtual decimal Import
	{
		get;
		set;
	}

}

