//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using References;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Дополнительно
/// </summary>
public class DriverAdditionalSetting
{
	/// <summary>
	/// Автоматически ставить подителя в сектор еназначения по GPS
	/// </summary>
	public virtual bool AutomaticallyPutTheDriverInTheSectorOfDestinationByGPS
	{
		get;
		set;
	}

	/// <summary>
	/// Автоматический пересчет долга (водитель работает по предоплате)
	/// </summary>
	public virtual bool AutomaticConversionOfDebtTheDriverOperatesOnPrepaidBasis
	{
		get;
		set;
	}

	/// <summary>
	/// Коэфициент начисления комиссонных
	/// </summary>
	public virtual decimal CommissionAccrualFactor
	{
		get;
		set;
	}

	/// <summary>
	/// Платит по факту (болеет, ремонт)
	/// </summary>
	public virtual bool PayingIntoTheIllRepair
	{
		get;
		set;
	}

	/// <summary>
	/// Если долг больше (Лимит задолжености)
	/// </summary>
	public virtual decimal LimitDebt
	{
		get;
		set;
	}

	/// <summary>
	/// Автоматически закрывать водителя
	/// Видит только безнал
	/// Не видит перекидку нал
	/// </summary>
	public virtual ActionInExcessOfTheAmountOfDebt ActionInExcessOfTheAmountOfDebt
	{
		get;
		set;
	}

	/// <summary>
	/// Не платит штраф за Отказ от своего заказа
	/// </summary>
	public virtual bool DoNotPayPenaltyForTheRefusalOfYourOrderFrom
	{
		get;
		set;
	}

	/// <summary>
	/// Не платит штраф заотказ от перекидочного заказа
	/// </summary>
	public virtual bool DoNotPayPenaltyForTheRefusalToImportOrder
	{
		get;
		set;
	}

	/// <summary>
	/// Не платит штраф за Отказ от своего заказа
	/// </summary>
	public virtual bool DoNotPayPenaltyForTheMorningOrder
	{
		get;
		set;
	}

}

