//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Персональная комиссия, %
/// </summary>
public class DriverPersonalCommission
{
	/// <summary>
	/// Нал (Свой)
	/// </summary>
	public virtual bool CashYour
	{
		get;
		set;
	}

	/// <summary>
	/// Безнал и терм. (Свой)
	/// </summary>
	public virtual decimal CashlessPaymentsYourValue
	{
		get;
		set;
	}

	/// <summary>
	/// Безнал и терм. (Свой)
	/// </summary>
	public virtual bool CashlessPaymentsYour
	{
		get;
		set;
	}

	/// <summary>
	/// Нал (Свой)
	/// </summary>
	public virtual decimal CashYourValue
	{
		get;
		set;
	}

	/// <summary>
	/// Безнал и терм. (Свой)
	/// </summary>
	public virtual bool CashlessPaymentsImport
	{
		get;
		set;
	}

	/// <summary>
	/// Безнал и терм. (Свой)
	/// </summary>
	public virtual decimal CashlessPaymentsImportValue
	{
		get;
		set;
	}

	/// <summary>
	/// Нал (Свой)
	/// </summary>
	public virtual bool CashImport
	{
		get;
		set;
	}

	/// <summary>
	/// Нал (Свой)
	/// </summary>
	public virtual decimal CashImportValue
	{
		get;
		set;
	}

}

